### ISSUE TITLE
Update Homework pdfs

### ISSUE THREAD

**Issue by lmiguelvargasf** [VoLuong/CS193A#1]
I really appreciate the time you took to make available these resources. I was wondering if it is possible to [update the homework](http://web.stanford.edu/class/cs193a/homework.shtml) pdf to the las version taught at Stanford?

Thanks in advance.

**Comment by luong-komorebi** [comment]
@bit0001  Sorry but I can't. All these resources are available thanks to a friend of mine but now he has graduated and I dont have the account to fetch all these updated Homework. I am very sorry
