### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by shivakrishna9** [VoLuong/CS193A#2]
I want to learn from your resource. How do I open the files in appropriate manner so that I can study the slides?

**Comment by luong-komorebi** [comment]
First of all, visit the official course page. You follow the order of the lessons listed there. Look at `link video.txt` , there is a link to the video of the courses. Inside `lectures` folder, there are pdf resource of each lesson. If you want to do the homework there is a homework folder for answer and stuffs, too. If you want Winter2017Update, dig into that folder to the slides folder and view them all. Hope it help.

**Comment by shivakrishna9** [comment]
Thank you.

**Comment by luong-komorebi** [comment]
No problem. Happy learning
